DA: false
autocast: true
# backbone: ViTS-224
# backbone: Convnext-T # CNN architecture
backbone: Swinv2S-256 # ViT architecture
batchsize: 16
block: 1
cj: 'no'
cls_loss: CELoss
data_dir: /Users/chibangnguyen/ayai/UAV/denseUAV_baseline/data/DenseUAV_data/train
droprate: 0.5
erasing_p: 0.3
feature_loss: WeightedSoftTripletLoss
gpu_ids: '0'
# h: 224
h: 256 # Swinv2S-256
# head: SingleBranch
head: SingleBranchCNN # CNN architecture, Swin architecture
# in_planes: 384
in_planes: 768 # Convnext-T, Swinv2S-256
kl_loss: KLLoss
load_from: 'no'
lr: 0.003
name: Loss_Experiment-CELoss-WeightedSoftTripletLoss_alpha10-KLLoss
nclasses: 2256
num_bottleneck: 512
num_epochs: 120
num_worker: 8
pad: 0
ra: satellite
re: satellite
rr: uav
sample_num: 1
share: true
use_gpu: true
# w: 224
w: 256 # Swinv2S-256
warm_epoch: 0
